---
- name: Cleanup demo Infra
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Find instances we created
      ec2_instance_info:
        filters:
          "tag:demo": 'true'
          instance-state-name: 'running'
      register: ec2_demo_instances

    - name: Delete Instances we created
      ec2:
        instance_ids: "{{ item.instance_id }}"
        state: absent
        wait: true
      with_items: "{{ ec2_demo_instances.instances }}"

    - name: Delete key we created
      ec2_key:
        name: demo_rsa_key
        state: absent

    - name: Find VPC we created
      ec2_vpc_net_info:
        filters:
          'tag:demo': 'true'
      register: demo_vpc


    - name: Find subnets we created
      ec2_vpc_subnet_info:
        filters:
          'tag:demo': 'true'
      register: demo_subnets

    - name: Delete subnets we created
      ec2_vpc_subnet:
        vpc_id: "{{ item.vpc_id }}"
        cidr: "{{ item.cidr_block }}"
        state: absent
      with_items: "{{ demo_subnets.subnets }}"

    - name: Find Security Groups we created
      ec2_group_info:
        filters:
          'tag:demo': "true"
      register: demo_sec_groups

    - name: Purge rules from groups
      ec2_group:
        description: "{{ item.description }}"
        purge_rules: true
        purge_rules_egress: true
        group_id: "{{ item.group_id }}"
        name: "{{ item.group_name }}"
      with_items: "{{ demo_sec_groups.security_groups }}"

    - name: Delete Security groups we created
      ec2_group:
        state: absent
        group_id: "{{ item.group_id }}"
      with_items: "{{ demo_sec_groups.security_groups }}"

    - name: Delete IGW we created
      ec2_vpc_igw:
        vpc_id: "{{ demo_vpc.vpcs[0].id }}"
        state: absent

    - name: Find route tables we created
      ec2_vpc_route_table_info:
        filters:
          vpc-id: "{{ demo_vpc.vpcs[0].id }}"
      register: demo_route_tables

    - name: Delete route tables we created
      ec2_vpc_route_table:
        state: absent
        route_table_id: "{{ item.id }}"
        vpc_id: "{{ item.vpc_id }}"
      with_items: "{{ demo_route_tables.route_tables }}"

    - name: Delete VPC we created
      ec2_vpc_net:
        name: Infra_VPC
        cidr_block: "{{ item.cidr_block }}"
        state: absent
        purge_cidrs: true
      with_items: "{{ demo_vpc.vpcs }}"
